### ISSUE TITLE
2.5.1加载卡在百分之32% 已修改前缀在前

### ISSUE THREAD

**Issue by 2351608249** [wohaopa/GTNHModify#1]
2.5.1加载卡在百分之32% 已修改前缀在前😥

**Comment by xiaolfc** [comment]
> 2.5.1加载卡在百分之32% 已修改前缀在前😥

我和你同样的问题

**Comment by xiaolfc** [comment]
> 2.5.1加载卡在百分之32% 已修改前缀在前😥

把前缀换成汉字可以解决，我刚成功了。

**Comment by xiaolfc** [comment]
> > 2.5.1加载卡在百分之32% 已修改前缀在前😥
> 
> 把前缀换成汉字可以解决，我刚成功了。

还是不行，卡在100%进不去游戏了

**Comment by wohaopa** [comment]
使用版本大于等于 `1.1.0` 的
